export const TAG_EN: Record<string, string> = {
  "Angststörungen": "Anxiety disorders",
  "Depression": "Depression",
  "Trauma": "Trauma",
  "Beziehungsprobleme": "Relationship issues",
  "Panikattacken": "Panic attacks",
  "Stress": "Stress",
  "Burnout": "Burnout",
  "Selbstwertprobleme": "Self-esteem issues",
  "PTBS": "PTSD",
  "Lebensübergänge": "Life transitions",
  "Stressbewältigung": "Stress management",
  "Work-Life-Balance": "Work-life balance",
  "Persönlichkeitsentwicklung": "Personal development",
  "Selbstwert": "Self-esteem",
  "Beziehungen": "Relationships",
  "Lebenskrisen": "Life crises",
  "Trauer": "Grief",
  "Angst": "Anxiety",
  "Bipolare Störung": "Bipolar disorder",
  "Schizophrenie": "Schizophrenia",
  "Medikation": "Medication",
  "Essstörungen": "Eating disorders",
  "Karriere": "Career",
  "Lebensveränderung": "Life change",
  "Schlafstörungen": "Sleep disorders",
  "Chronischer Stress": "Chronic stress",
  "Paarkonflikte": "Couple conflicts",
  "Trennungsschmerz": "Separation pain",
  "Studiumsstress": "Academic stress",
  "Soziale Angst": "Social anxiety",
  "ADHS": "ADHD",
  "Autismus-Spektrum": "Autism spectrum",
  "Persönlichkeitsstörungen": "Personality disorders",
  "Bindungsangst": "Attachment anxiety",
  "Sinnfragen": "Meaning & purpose",
  "Affektive Störungen": "Affective disorders",
  "Sucht": "Addiction",
  "Phobien": "Phobias",
  "Zwangsstörungen": "OCD",
  "Migration": "Migration",
  "Kulturelle Identität": "Cultural identity",
  "Abhängigkeit": "Dependency",
};


export const ROLE_EN: Record<string, string> = {
  "Klinische Psychologin": "Clinical Psychologist",
  "Klinische Psychologin (PhD)": "Clinical Psychologist (PhD)",
  "Klinischer Psychologe (PhD)": "Clinical Psychologist (PhD)",
  "Psychologischer Psychotherapeut": "Psychological Psychotherapist",
  "Psychologischer Psychotherapeut (M.Sc.)": "Psychological Psychotherapist (M.Sc.)",
  "Fachärztin für Psychiatrie": "Specialist in Psychiatry",
  "Fachärztin für Psychiatrie (Dr. med.)": "Specialist in Psychiatry (Dr. med.)",
  "Facharzt für Psychiatrie": "Specialist in Psychiatry",
  "Facharzt für Psychiatrie (Dr. med.)": "Specialist in Psychiatry (Dr. med.)",
  "Lebens- und Sozialberater": "Life & Social Counsellor",
  "Lebens- und Sozialberater (Dipl.)": "Life & Social Counsellor (Dipl.)",
  "Psychologin (M.Sc.)": "Psychologist (M.Sc.)",
  "Diplom-Psychologe": "Psychologist (Dipl.)",
  "Psychotherapeutin": "Psychotherapist",
  "Psychotherapeutin (Mag.)": "Psychotherapist (Mag.)",
};

export const ARBEITSWEISE_EN: Record<string, string> = {
  "Empathisch": "Empathetic",
  "Strukturiert": "Structured",
  "Evidenzbasiert": "Evidence-based",
  "Lösungsorientiert": "Solution-focused",
  "Systemisch": "Systemic",
  "Ressourcenorientiert": "Resource-oriented",
  "Praktisch": "Practical",
  "Unterstützend": "Supportive",
  "Ganzheitlich": "Holistic",
  "Praxisnah": "Practice-oriented",
  "Lösungsfokussiert": "Solution-focused",
  "Wertfrei": "Non-judgmental",
  "Ermutigend": "Encouraging",
  "Reflektierend": "Reflective",
  "Einfühlsam": "Empathetic",
  "Tiefgreifend": "In-depth",
  "Warm": "Warm",
  "Motivierend": "Motivating",
  "Entwicklungsorientiert": "Growth-oriented",
  "Präzise": "Precise",
  "Erfahren": "Experienced",
  "Traumasensibel": "Trauma-sensitive",
  "Geduldig": "Patient",
  "Heilungsorientiert": "Healing-oriented",
  "Sicher": "Safe",
  "Medizinisch fundiert": "Medically grounded",
  "Individuell": "Individual",
  "Fürsorglich": "Caring",
  "Wissenschaftlich": "Scientific",
  "Nachhaltig": "Sustainable",
  "Systematisch": "Systematic",
  "Neutral": "Neutral",
  "Klar": "Clear",
  "Verständnisvoll": "Understanding",
  "Spezialisiert": "Specialised",
  "Fundiert": "Well-grounded",
  "KVT-basiert": "CBT-based",
  "Kulturell sensibel": "Culturally sensitive",
  "Inklusiv": "Inclusive",
  "Ohne Vorurteile": "Non-prejudiced",
  "Bindungsorientiert": "Attachment-oriented",
  "Heilend": "Healing",
  "Sinnorientiert": "Meaning-oriented",
  "Authentisch": "Authentic",
  "Expertenhaft": "Expert",
  "Umfassend": "Comprehensive",
  "Altersgerecht": "Age-appropriate",
  "Ermächtigend": "Empowering",
  "Stabil": "Stable",
};

export const QUAL_TITLE_EN: Record<string, string> = {
  "PhD in Klinischer Psychologie": "PhD in Clinical Psychology",
  "MSc in Psychologie": "MSc in Psychology",
  "M.Sc. Psychologie": "M.Sc. in Psychology",
  "Postgraduale Ausbildung in traumafokussierter KVT": "Postgraduate training in trauma-focused CBT",
  "Approbierte Psychologin": "Licensed Psychologist",
  "Zertifizierung: EuroPsy": "Certification: EuroPsy",
  "Ausbildung Verhaltenstherapie": "Behavioural therapy training",
  "Zertifizierung Stressbewältigung": "Stress management certification",
  "Dr. med. Psychiatrie": "Dr. med. Psychiatry",
  "Fachärztin für Psychiatrie": "Specialist in Psychiatry",
  "Facharzt für Psychiatrie": "Specialist in Psychiatry",
  "Zusatzausbildung Traumatherapie": "Additional training in trauma therapy",
  "Diplom Lebens- und Sozialberatung": "Diploma in Life & Social Counselling",
  "Ausbildung Stressmanagement": "Stress management training",
  "Zertifizierung Burnout-Prävention": "Burnout prevention certification",
  "Coaching-Ausbildung": "Coaching training",
  "Zertifizierung Positive Psychologie": "Positive psychology certification",
  "Diplom Psychologie": "Diploma in Psychology",
  "Ausbildung Krisenintervention": "Crisis intervention training",
  "Zertifizierung Trauerbegleitung": "Grief counselling certification",
  "Ausbildung EMDR": "EMDR training",
  "Zertifizierung Essstörungen": "Eating disorders certification",
  "Mag. Psychologie": "Mag. in Psychology",
  "Ausbildung Junge Erwachsene": "Training for young adults",
  "Zusatzausbildung ADHS": "Additional training in ADHD",
  "Zertifizierung Autismus": "Autism certification",
  "Psychotherapieausbildung": "Psychotherapy training",
  "Zertifizierung Bindungstherapie": "Attachment therapy certification",
  "Lebens- und Sozialberatung": "Life & Social Counselling",
  "Persönlichkeitsentwicklung": "Personal development",
  "Zertifizierung Suchttherapie": "Addiction therapy certification",
  "Schlafmedizin Zertifizierung": "Sleep medicine certification",
  "Approbation Klinische Psychologie": "Approbation in Clinical Psychology",
  "PhD Klinische Psychologie": "PhD in Clinical Psychology",
  "Transkulturelle Psychologie": "Transcultural Psychology",
  "KVT Ausbildung": "CBT training",
  "Zertifizierung Angststörungen": "Anxiety disorders certification",
  "Zusatzausbildung Neuropsychiatrie": "Additional training in Neuropsychiatry",
  "Karriereberatung": "Career counselling",
  "Paarberatung Ausbildung": "Couple counselling training",
};
export const therapists = [
  {
    id: 1,
    name: "Dr. Sarah Müller",
    role: "Klinische Psychologin",
    degree: "Klinische Psychologin (PhD)",
    roleIcon: "/icons/role-brain.svg",
    photo: "/fachkraefte/fachkraft-1.jpg",
    photoDetail: "/fachkraefte/fachkraft-1.jpg",
    experience: 12,
    location: "Wien",
    stars: 4.9,
    reviewCount: 32,
    languages: ["Deutsch", "Englisch"],
    tags: ["Angststörungen", "Depression", "Trauma", "Beziehungsprobleme", "Panikattacken"],
    kassenerstattung: true,
    verified: true,
    price: 85,
    sessionDuration: 50,
    availability: "today",
    availabilityText: "Heute verfügbar",
    nextAppointment: "Heute, 16:00",
    angebot: "beides",
    bio: "Mir ist wichtig, dass Du Dich verstanden und nicht bewertet fühlst. Ich begleite Menschen mit Empathie, Klarheit und einem offenen Blick für ihre individuelle Situation.",
    bio_en: "It matters to me that you feel understood and not judged. I accompany people with empathy, clarity and an open perspective for their individual situation.",
    approach_en: "Every person brings their own history, challenges and strengths. That is why there are no one-size-fits-all solutions for me.\n\nTogether we look at what is weighing on you right now, and step by step we develop new perspectives and paths that suit your life.\n\nI combine scientifically grounded methods with empathy, clarity and a trusting collaboration as equals.",
    approach: "Jeder Mensch bringt seine eigene Geschichte, Herausforderungen und Stärken mit. Deshalb gibt es für mich keine Lösungen von der Stange.\n\nGemeinsam schauen wir auf das, was Dich aktuell belastet, und entwickeln Schritt für Schritt neue Perspektiven und Wege, die zu Deinem Leben passen.\n\nDabei verbinde ich wissenschaftlich fundierte Methoden mit Empathie, Klarheit und einer vertrauensvollen Zusammenarbeit auf Augenhöhe.",
    arbeitsweise: ["Empathisch", "Strukturiert", "Evidenzbasiert", "Lösungsorientiert"],
    qualifikationen: [
      { year: "2016", title: "PhD in Klinischer Psychologie", institution: "Universität Wien" },
      { year: "2012", title: "MSc in Psychologie", institution: "Universität Wien" },
      { year: "2010", title: "Postgraduale Ausbildung in traumafokussierter KVT", institution: "Österreichische Gesellschaft für Verhaltenstherapie" },
      { year: "2009", title: "Approbierte Psychologin", institution: "Gesundheitsministerium Österreich" },
      { year: "2008", title: "Zertifizierung: EuroPsy", institution: "Europäische Föderation der Psychologenverbände" },
    ],
    address: { street: "Mariahilfer Straße 45", city: "1060 Wien" },
  },
  {
    id: 2,
    name: "Michael Weber",
    role: "Psychologischer Psychotherapeut",
    degree: "Psychologischer Psychotherapeut (M.Sc.)",
    roleIcon: "/icons/role-hilfe.svg",
    photo: "/fachkraefte/fachkraft-2.jpg",
    photoDetail: "/fachkraefte/fachkraft-2.jpg",
    experience: 8,
    location: "Graz",
    stars: 4.8,
    reviewCount: 18,
    languages: ["Deutsch", "Französisch"],
    tags: ["Angststörungen", "Stress", "Burnout", "Selbstwertprobleme"],
    kassenerstattung: true,
    verified: true,
    price: 75,
    sessionDuration: 50,
    availability: "later",
    availabilityText: "Nächster Termin in 2 Wochen",
    nextAppointment: "28. Mai, 10:00",
    angebot: "online",
    bio: "Mit Geduld und Verständnis begleite ich Dich auf Deinem Weg zu mehr Stabilität und innerer Stärke.",
    bio_en: "With patience and understanding I accompany you on your path to greater stability and inner strength.",
    approach_en: "I work systemically and resource-oriented. In our shared process we look at the strengths you already bring — and how we can put them to targeted use.\n\nMy goal is to give you practical tools that you can genuinely use in everyday life.",
    approach: "Ich arbeite systemisch und ressourcenorientiert. In unserem gemeinsamen Prozess schauen wir, welche Stärken Du bereits mitbringst – und wie wir diese gezielt einsetzen können.\n\nMein Ziel ist es, Dir praktische Werkzeuge an die Hand zu geben, die Du im Alltag wirklich nutzen kannst.",
    arbeitsweise: ["Systemisch", "Ressourcenorientiert", "Praktisch", "Unterstützend"],
    qualifikationen: [
      { year: "2015", title: "M.Sc. Psychologie", institution: "Karl-Franzens-Universität Graz" },
      { year: "2017", title: "Ausbildung Verhaltenstherapie", institution: "Österreichische Gesellschaft für Verhaltenstherapie" },
      { year: "2019", title: "Zertifizierung Stressbewältigung", institution: "Österreichisches Bundesinstitut für Gesundheitswesen" },
    ],
    address: { street: "Hauptplatz 12", city: "8010 Graz" },
  },
  {
    id: 3,
    name: "Dr. Anna Schmidt",
    role: "Fachärztin für Psychiatrie",
    degree: "Fachärztin für Psychiatrie (Dr. med.)",
    roleIcon: "/icons/role-psychotherapie.svg",
    photo: "/fachkraefte/fachkraft-3.jpg",
    photoDetail: "/fachkraefte/fachkraft-3.jpg",
    experience: 15,
    location: "Salzburg",
    stars: 4.9,
    reviewCount: 27,
    languages: ["Deutsch", "Englisch", "Italienisch"],
    tags: ["Trauma", "PTBS", "Angststörungen", "Depression"],
    kassenerstattung: true,
    verified: true,
    price: 95,
    sessionDuration: 50,
    availability: "thisweek",
    availabilityText: "Verfügbar diese Woche",
    nextAppointment: "Fr. 16. Mai, 14:00",
    angebot: "vor-ort",
    bio: "Als Fachärztin verbinde ich medizinisches Wissen mit tiefem psychologischem Verständnis für Deine Situation.",
    bio_en: "As a specialist physician I combine medical knowledge with a deep psychological understanding of your situation.",
    approach_en: "Psychiatric support means to me: seeing the person as a whole — body, mind and environment. I work closely with you to develop an individual treatment plan.\n\nMy strength lies in the combination of medical expertise and human warmth.",
    approach: "Psychiatrische Unterstützung bedeutet für mich: Den Menschen als Ganzes sehen – Körper, Geist und Umfeld. Ich arbeite eng mit Dir zusammen, um einen individuellen Behandlungsplan zu entwickeln.\n\nMeine Stärke liegt in der Verbindung von medizinischer Expertise und menschlicher Wärme.",
    arbeitsweise: ["Ganzheitlich", "Medizinisch fundiert", "Individuell", "Fürsorglich"],
    qualifikationen: [
      { year: "2008", title: "Dr. med. Psychiatrie", institution: "Paracelsus Medizinische Privatuniversität Salzburg" },
      { year: "2011", title: "Fachärztin für Psychiatrie", institution: "Österreichische Ärztekammer" },
      { year: "2014", title: "Zusatzausbildung Traumatherapie", institution: "EMDR Austria" },
    ],
    address: { street: "Nonntaler Hauptstraße 8", city: "5020 Salzburg" },
  },
  {
    id: 4,
    name: "Thomas Becker",
    role: "Lebens- und Sozialberater",
    degree: "Lebens- und Sozialberater (Dipl.)",
    roleIcon: "/icons/role-herz.svg",
    photo: "/fachkraefte/fachkraft-4.jpg",
    photoDetail: "/fachkraefte/fachkraft-4.jpg",
    experience: 6,
    location: "Linz",
    stars: 4.7,
    reviewCount: 14,
    languages: ["Deutsch"],
    tags: ["Burnout", "Work-Life-Balance", "Lebensübergänge", "Stressbewältigung"],
    kassenerstattung: true,
    verified: true,
    price: 70,
    sessionDuration: 50,
    availability: "thisweek",
    availabilityText: "Nächster Termin in 1 Woche",
    nextAppointment: "Mi. 21. Mai, 11:00",
    angebot: "beides",
    bio: "Ich helfe Dir, klare Prioritäten zu setzen und Deinen Alltag so zu gestalten, dass er sich wieder richtig anfühlt.",
    bio_en: "I help you to set clear priorities and shape your daily life so that it feels right again.",
    approach_en: "In my work as a life and social counsellor I accompany people through processes of change. Together we develop strategies adapted to your concrete life circumstances.\n\nI value practical, down-to-earth counselling that you can implement immediately in everyday life.",
    approach: "In meiner Arbeit als Lebens- und Sozialberater begleite ich Menschen in Veränderungsprozessen. Gemeinsam erarbeiten wir Strategien, die Deinen konkreten Lebensumständen angepasst sind.\n\nIch lege Wert auf eine praxisnahe Beratung, die Du sofort im Alltag umsetzen kannst.",
    arbeitsweise: ["Praxisnah", "Lösungsfokussiert", "Unterstützend", "Klar"],
    qualifikationen: [
      { year: "2017", title: "Diplom Lebens- und Sozialberatung", institution: "WIFI Österreich" },
      { year: "2019", title: "Ausbildung Stressmanagement", institution: "Österreichischer Berufsverband für Lebens- und Sozialberatung" },
      { year: "2020", title: "Zertifizierung Burnout-Prävention", institution: "Institut für Persönlichkeitsentwicklung Wien" },
    ],
    address: { street: "Landstraße 47", city: "4020 Linz" },
  },
  {
    id: 5,
    name: "Julia Berger",
    role: "Psychologin (M.Sc.)",
    degree: "Psychologin (M.Sc.)",
    roleIcon: "/icons/role-brain.svg",
    photo: "/fachkraefte/fachkraft-5.jpg",
    photoDetail: "/fachkraefte/fachkraft-5.jpg",
    experience: 5,
    location: "Wien",
    stars: 4.6,
    reviewCount: 11,
    languages: ["Deutsch", "Englisch"],
    tags: ["Selbstwert", "Persönlichkeitsentwicklung", "Stress"],
    kassenerstattung: false,
    verified: true,
    price: 80,
    sessionDuration: 50,
    availability: "today",
    availabilityText: "Heute verfügbar",
    nextAppointment: "Heute, 18:00",
    angebot: "online",
    bio: "Gemeinsam stärken wir Dein Selbstbewusstsein und entwickeln Dein volles Potenzial.",
    bio_en: "Together we strengthen your self-confidence and develop your full potential.",
    approach_en: "I accompany you in getting to know yourself better and unfolding your resources. In a non-judgmental space you explore what drives you — and what holds you back.\n\nMy approach combines psychology with concrete techniques for personal development.",
    approach: "Ich begleite Dich dabei, Dich selbst besser kennenzulernen und Deine Ressourcen zu entfalten. In einem wertfreien Raum erforschst Du, was Dich antreibt – und was Dich zurückhält.\n\nMein Ansatz verbindet Psychologie mit konkreten Techniken zur Persönlichkeitsentwicklung.",
    arbeitsweise: ["Wertfrei", "Ermutigend", "Reflektierend", "Entwicklungsorientiert"],
    qualifikationen: [
      { year: "2018", title: "M.Sc. Psychologie", institution: "Universität Wien" },
      { year: "2020", title: "Coaching-Ausbildung", institution: "Österreichischer Coaching-Dachverband" },
      { year: "2021", title: "Zertifizierung Positive Psychologie", institution: "Institut für Positive Psychologie Wien" },
    ],
    address: null,
  },
  {
    id: 6,
    name: "Markus Hofmann",
    role: "Diplom-Psychologe",
    degree: "Diplom-Psychologe",
    roleIcon: "/icons/role-hilfe.svg",
    photo: "/fachkraefte/fachkraft-6.jpg",
    photoDetail: "/fachkraefte/fachkraft-6.jpg",
    experience: 10,
    location: "Innsbruck",
    stars: 4.8,
    reviewCount: 23,
    languages: ["Deutsch"],
    tags: ["Depression", "Lebenskrisen", "Trauer"],
    kassenerstattung: true,
    verified: true,
    price: 90,
    sessionDuration: 50,
    availability: "later",
    availabilityText: "Nächster Termin in 3 Wochen",
    nextAppointment: "2. Jun, 09:00",
    angebot: "vor-ort",
    bio: "In schwierigen Lebensphasen bin ich ein verlässlicher Begleiter – ohne Urteile, mit echtem Verständnis.",
    bio_en: "In difficult phases of life I am a reliable companion — without judgement, with genuine understanding.",
    approach_en: "Crises are part of life — but you do not have to go through them alone. I offer you a safe space where you can voice everything that weighs on you.\n\nTogether we find ways to bring stability and lightness back into your everyday life.",
    approach: "Krisen gehören zum Leben – aber Du musst sie nicht alleine durchstehen. Ich biete Dir einen sicheren Rahmen, in dem Du alles aussprechen kannst, was Dich belastet.\n\nGemeinsam finden wir Wege, wie Du wieder Stabilität und Leichtigkeit in Deinen Alltag bringen kannst.",
    arbeitsweise: ["Einfühlsam", "Stabil", "Tiefgreifend", "Unterstützend"],
    qualifikationen: [
      { year: "2013", title: "Diplom Psychologie", institution: "Universität Innsbruck" },
      { year: "2015", title: "Ausbildung Krisenintervention", institution: "Österreichisches Rotes Kreuz" },
      { year: "2017", title: "Zertifizierung Trauerbegleitung", institution: "Österreichische Gesellschaft für Trauerbegleitung" },
    ],
    address: { street: "Maria-Theresien-Straße 3", city: "6020 Innsbruck" },
  },
  {
    id: 7, name: "Sophia Gruber", role: "Psychologin (M.Sc.)", degree: "Psychologin (M.Sc.)", photo: "/fachkraefte/fachkraft-1.jpg", photoDetail: "/fachkraefte/fachkraft-1.jpg", experience: 4, location: "Wien", stars: 4.7, reviewCount: 9, languages: ["Deutsch", "Englisch"], tags: ["Selbstwert", "Angst", "Stress", "Beziehungen"], kassenerstattung: false, verified: true, price: 75, sessionDuration: 50, availability: "today", availabilityText: "Heute verfügbar", nextAppointment: "Heute, 19:00", angebot: "online", bio: "Ich unterstütze Dich dabei, Deine Stärken zu entdecken und Herausforderungen mit neuem Selbstvertrauen zu begegnen.",
    bio_en: "I support you in discovering your strengths and meeting challenges with new confidence.",
    approach_en: "My work is based on a resource-oriented approach. Together we look at what you already bring — and how we can put that to targeted use.", approach: "Meine Arbeit basiert auf einem ressourcenorientierten Ansatz. Gemeinsam schauen wir, was Du bereits mitbringst – und wie wir das gezielt einsetzen können.", arbeitsweise: ["Ressourcenorientiert", "Warm", "Strukturiert", "Motivierend"], qualifikationen: [{ year: "2019", title: "M.Sc. Psychologie", institution: "Universität Wien" }, { year: "2021", title: "Ausbildung Verhaltenstherapie", institution: "Österreichische Gesellschaft für Verhaltenstherapie" }], address: null,
  },
  {
    id: 8, address: { street: "Glacisstraße 17", city: "8010 Graz" }, name: "Dr. Klaus Wagner", role: "Facharzt für Psychiatrie", degree: "Facharzt für Psychiatrie (Dr. med.)", photo: "/fachkraefte/fachkraft-2.jpg", photoDetail: "/fachkraefte/fachkraft-2.jpg", experience: 20, location: "Graz", stars: 4.9, reviewCount: 41, languages: ["Deutsch"], tags: ["Depression", "Bipolare Störung", "Schizophrenie", "Medikation"], kassenerstattung: true, verified: true, price: 120, sessionDuration: 50, availability: "thisweek", availabilityText: "Verfügbar diese Woche", nextAppointment: "Do. 22. Mai, 10:00", angebot: "vor-ort", bio: "Mit 20 Jahren Erfahrung biete ich fundierte psychiatrische Diagnostik und Behandlung auf höchstem Niveau.",
    bio_en: "With 20 years of experience I offer sound psychiatric diagnostics and treatment at the highest level.",
    approach_en: "Psychiatric conditions require a deep understanding of biological, psychological and social factors. I develop with you an individual, evidence-based treatment plan.", approach: "Psychiatrische Erkrankungen erfordern ein tiefes Verständnis der biologischen, psychologischen und sozialen Faktoren. Ich entwickle mit Dir einen individuellen, evidenzbasierten Behandlungsplan.", arbeitsweise: ["Evidenzbasiert", "Präzise", "Ganzheitlich", "Erfahren"], qualifikationen: [{ year: "2003", title: "Dr. med. Psychiatrie", institution: "Medizinische Universität Graz" }, { year: "2006", title: "Facharzt Psychiatrie", institution: "Österreichische Ärztekammer" }, { year: "2010", title: "Zusatzausbildung Neuropsychiatrie", institution: "Europäische Psychiatrische Vereinigung" }],
  },
  {
    id: 9, address: { street: "Paris-Lodron-Straße 6", city: "5020 Salzburg" }, name: "Elena Koch", role: "Psychotherapeutin", degree: "Psychotherapeutin (Mag.)", photo: "/fachkraefte/fachkraft-3.jpg", photoDetail: "/fachkraefte/fachkraft-3.jpg", experience: 9, location: "Salzburg", stars: 4.8, reviewCount: 22, languages: ["Deutsch", "Englisch", "Russisch"], tags: ["Trauma", "PTBS", "Essstörungen", "Angststörungen"], kassenerstattung: true, verified: true, price: 95, sessionDuration: 50, availability: "thisweek", availabilityText: "Verfügbar diese Woche", nextAppointment: "Mi. 21. Mai, 15:00", angebot: "beides", bio: "Ich begleite Menschen mit Trauma und Essstörungen auf ihrem Weg zu Heilung und Selbstakzeptanz.",
    bio_en: "I accompany people with trauma and eating disorders on their path to healing and self-acceptance.",
    approach_en: "Trauma therapy requires sensitivity and patience. I work in a trauma-sensitive way and always adapt the pace to your needs.", approach: "Traumatherapie erfordert Feingefühl und Geduld. Ich arbeite traumasensibel und passe das Tempo immer Deinen Bedürfnissen an.", arbeitsweise: ["Traumasensibel", "Geduldig", "Heilungsorientiert", "Sicher"], qualifikationen: [{ year: "2014", title: "Mag. Psychologie", institution: "Universität Salzburg" }, { year: "2016", title: "Ausbildung EMDR", institution: "EMDR Austria" }, { year: "2018", title: "Zertifizierung Essstörungen", institution: "Österreichische Gesellschaft für Essstörungen" }],
  },
  {
    id: 10, address: null, name: "Felix Maier", role: "Lebens- und Sozialberater", degree: "Lebens- und Sozialberater", photo: "/fachkraefte/fachkraft-4.jpg", photoDetail: "/fachkraefte/fachkraft-4.jpg", experience: 3, location: "Wien", stars: 4.6, reviewCount: 7, languages: ["Deutsch"], tags: ["Work-Life-Balance", "Burnout", "Karriere", "Lebensveränderung"], kassenerstattung: false, verified: false, price: 65, sessionDuration: 50, availability: "today", availabilityText: "Heute verfügbar", nextAppointment: "Heute, 17:30", angebot: "online", bio: "Ich unterstütze Dich dabei, Dein Leben so zu gestalten, wie Du es Dir wünschst.",
    bio_en: "I support you in shaping your life the way you want it to be.",
    approach_en: "Change begins with clarity. Together we identify what truly matters to you — and develop concrete steps in the desired direction.", approach: "Veränderung beginnt mit Klarheit. Gemeinsam identifizieren wir, was Dir wirklich wichtig ist – und entwickeln konkrete Schritte in die gewünschte Richtung.", arbeitsweise: ["Klar", "Motivierend", "Praktisch", "Unterstützend"], qualifikationen: [{ year: "2020", title: "Lebens- und Sozialberatung", institution: "WIFI Wien" }, { year: "2021", title: "Karriereberatung", institution: "Wirtschaftskammer Österreich" }],
  },
  {
    id: 11, address: { street: "Anichstraße 35", city: "6020 Innsbruck" }, name: "Dr. Christine Steiner", role: "Klinische Psychologin", degree: "Klinische Psychologin (PhD)", photo: "/fachkraefte/fachkraft-5.jpg", photoDetail: "/fachkraefte/fachkraft-5.jpg", experience: 14, location: "Innsbruck", stars: 4.8, reviewCount: 31, languages: ["Deutsch", "Englisch"], tags: ["Depression", "Angststörungen", "Schlafstörungen", "Chronischer Stress"], kassenerstattung: true, verified: true, price: 90, sessionDuration: 50, availability: "later", availabilityText: "Nächster Termin in 2 Wochen", nextAppointment: "3. Jun, 11:00", angebot: "beides", bio: "Mit wissenschaftlich fundierten Methoden helfe ich Dir, Deine psychische Gesundheit nachhaltig zu stärken.",
    bio_en: "With scientifically grounded methods I help you to sustainably strengthen your mental health.",
    approach_en: "Mental health is not a luxury — it is the foundation for everything else. I work with you on lasting solutions that improve your wellbeing in the long term.", approach: "Psychische Gesundheit ist kein Luxus – sie ist die Grundlage für alles andere. Ich arbeite mit Dir an nachhaltigen Lösungen, die Dein Wohlbefinden langfristig verbessern.", arbeitsweise: ["Wissenschaftlich", "Nachhaltig", "Systematisch", "Fürsorglich"], qualifikationen: [{ year: "2009", title: "PhD Klinische Psychologie", institution: "Universität Innsbruck" }, { year: "2011", title: "Approbation Klinische Psychologie", institution: "Österreichische Gesellschaft für Psychologie" }, { year: "2014", title: "Schlafmedizin Zertifizierung", institution: "Österreichische Gesellschaft für Schlafmedizin" }],
  },
  {
    id: 12, address: { street: "Linzer Straße 22", city: "4020 Linz" }, name: "Robert Huber", role: "Diplom-Psychologe", degree: "Diplom-Psychologe", photo: "/fachkraefte/fachkraft-6.jpg", photoDetail: "/fachkraefte/fachkraft-6.jpg", experience: 7, location: "Linz", stars: 4.7, reviewCount: 16, languages: ["Deutsch"], tags: ["Paarkonflikte", "Trennungsschmerz", "Lebenskrisen"], kassenerstattung: false, verified: true, price: 75, sessionDuration: 50, availability: "thisweek", availabilityText: "Verfügbar diese Woche", nextAppointment: "Di. 20. Mai, 13:00", angebot: "vor-ort", bio: "In Beziehungsfragen und Lebenskrisen biete ich Orientierung und einen klaren Blick von außen.",
    bio_en: "In relationship matters and life crises I offer orientation and a clear outside perspective.",
    approach_en: "Relationships are complex — and sometimes you need a neutral view. I accompany you in recognising patterns and finding new paths.", approach: "Beziehungen sind komplex – und manchmal braucht man einen neutralen Blick. Ich begleite Dich dabei, Muster zu erkennen und neue Wege zu finden.", arbeitsweise: ["Neutral", "Klar", "Verständnisvoll", "Lösungsorientiert"], qualifikationen: [{ year: "2016", title: "Diplom Psychologie", institution: "Universität Linz" }, { year: "2018", title: "Paarberatung Ausbildung", institution: "Österreichischer Berufsverband für Psychotherapie" }],
  },
  {
    id: 13, address: null, name: "Laura Fischer", role: "Psychologin (M.Sc.)", degree: "Psychologin (M.Sc.)", photo: "/fachkraefte/fachkraft-1.jpg", photoDetail: "/fachkraefte/fachkraft-1.jpg", experience: 3, location: "Wien", stars: 4.5, reviewCount: 8, languages: ["Deutsch", "Englisch"], tags: ["Studiumsstress", "Selbstwert", "Soziale Angst"], kassenerstattung: false, verified: true, price: 65, sessionDuration: 50, availability: "today", availabilityText: "Heute verfügbar", nextAppointment: "Heute, 20:00", angebot: "online", bio: "Ich verstehe die besonderen Herausforderungen junger Erwachsener und biete einfühlsame Unterstützung.",
    bio_en: "I understand the particular challenges of young adults and offer empathetic support.",
    approach_en: "Young people face unique challenges. I offer a safe space where you can try things out and grow.", approach: "Junge Menschen stehen vor einzigartigen Herausforderungen. Ich biete einen sicheren Raum, in dem Du Dich ausprobieren und wachsen kannst.", arbeitsweise: ["Einfühlsam", "Altersgerecht", "Ermächtigend", "Warm"], qualifikationen: [{ year: "2021", title: "M.Sc. Psychologie", institution: "Universität Wien" }, { year: "2022", title: "Ausbildung Junge Erwachsene", institution: "Institut für Jugendpsychologie Wien" }],
  },
  {
    id: 14, address: { street: "Währinger Gürtel 18", city: "1090 Wien" }, name: "Dr. Martin Wolf", role: "Facharzt für Psychiatrie", degree: "Facharzt für Psychiatrie (Dr. med.)", photo: "/fachkraefte/fachkraft-2.jpg", photoDetail: "/fachkraefte/fachkraft-2.jpg", experience: 22, location: "Wien", stars: 5.0, reviewCount: 54, languages: ["Deutsch", "Englisch"], tags: ["ADHS", "Autismus-Spektrum", "Angststörungen", "Depression", "Persönlichkeitsstörungen"], kassenerstattung: true, verified: true, price: 130, sessionDuration: 50, availability: "later", availabilityText: "Nächster Termin in 3 Wochen", nextAppointment: "5. Jun, 09:00", angebot: "vor-ort", bio: "Als erfahrener Facharzt mit 22 Jahren Praxis biete ich umfassende psychiatrische Diagnostik und Behandlung.",
    bio_en: "As an experienced specialist with 22 years of practice I offer comprehensive psychiatric diagnostics and treatment.",
    approach_en: "Complex psychiatric conditions require expertise and experience. With my broad knowledge I develop a tailored therapy plan for each patient.", approach: "Komplexe psychiatrische Erkrankungen erfordern Expertise und Erfahrung. Mit meinem breiten Fachwissen entwickle ich für jeden Patienten einen maßgeschneiderten Therapieplan.", arbeitsweise: ["Expertenhaft", "Umfassend", "Evidenzbasiert", "Individuell"], qualifikationen: [{ year: "2001", title: "Dr. med. Psychiatrie", institution: "Medizinische Universität Wien" }, { year: "2004", title: "Facharzt Psychiatrie", institution: "Österreichische Ärztekammer" }, { year: "2008", title: "Zusatzausbildung ADHS", institution: "Österreichische ADHS-Gesellschaft" }, { year: "2012", title: "Zertifizierung Autismus", institution: "Österreichische Autistenhilfe" }],
  },
  {
    id: 15, address: { street: "Schubertstraße 11", city: "8010 Graz" }, name: "Nina Brunner", role: "Psychotherapeutin", degree: "Psychotherapeutin (Mag.)", photo: "/fachkraefte/fachkraft-3.jpg", photoDetail: "/fachkraefte/fachkraft-3.jpg", experience: 11, location: "Graz", stars: 4.8, reviewCount: 26, languages: ["Deutsch", "Spanisch"], tags: ["Bindungsangst", "Beziehungsprobleme", "Trauma", "Selbstwert"], kassenerstattung: true, verified: true, price: 85, sessionDuration: 50, availability: "thisweek", availabilityText: "Verfügbar diese Woche", nextAppointment: "Fr. 23. Mai, 10:00", angebot: "beides", bio: "Ich begleite Dich dabei, alte Bindungsmuster zu verstehen und gesündere Beziehungen zu Dir und anderen aufzubauen.",
    bio_en: "I accompany you in understanding old attachment patterns and building healthier relationships with yourself and others.",
    approach_en: "Attachment and relationships are fundamental human needs. I help you to understand and transform your attachment patterns.", approach: "Bindung und Beziehung sind grundlegende menschliche Bedürfnisse. Ich helfe Dir, Deine Bindungsmuster zu verstehen und zu transformieren.", arbeitsweise: ["Bindungsorientiert", "Tiefgreifend", "Heilend", "Sicher"], qualifikationen: [{ year: "2012", title: "Mag. Psychologie", institution: "Universität Graz" }, { year: "2015", title: "Psychotherapieausbildung", institution: "Österreichischer Bundesverband für Psychotherapie" }, { year: "2017", title: "Zertifizierung Bindungstherapie", institution: "Institut für Bindungsforschung Graz" }],
  },
  {
    id: 16, address: null, name: "Andreas Keller", role: "Lebens- und Sozialberater", degree: "Lebens- und Sozialberater", photo: "/fachkraefte/fachkraft-4.jpg", photoDetail: "/fachkraefte/fachkraft-4.jpg", experience: 5, location: "Wien", stars: 4.6, reviewCount: 12, languages: ["Deutsch"], tags: ["Sinnfragen", "Lebensübergänge", "Persönlichkeitsentwicklung"], kassenerstattung: false, verified: false, price: 60, sessionDuration: 50, availability: "today", availabilityText: "Heute verfügbar", nextAppointment: "Heute, 15:00", angebot: "online", bio: "Ich unterstütze Dich bei der Suche nach Sinn und Orientierung in wichtigen Lebensphasen.",
    bio_en: "I support you in finding meaning and orientation in important phases of life.",
    approach_en: "Life transitions can be challenging — but they also offer the chance for genuine growth. Together you explore what truly matters to you.", approach: "Lebensübergänge können herausfordernd sein – aber sie bieten auch die Chance für echtes Wachstum. Gemeinsam erforschst Du, was Dir wirklich wichtig ist.", arbeitsweise: ["Sinnorientiert", "Reflektierend", "Ermutigend", "Authentisch"], qualifikationen: [{ year: "2018", title: "Lebens- und Sozialberatung", institution: "WIFI Wien" }, { year: "2020", title: "Persönlichkeitsentwicklung", institution: "Institut für Systemische Beratung Wien" }],
  },
  {
    id: 17, address: { street: "Faberstraße 4", city: "5020 Salzburg" }, name: "Dr. Eva Zimmermann", role: "Fachärztin für Psychiatrie", degree: "Fachärztin für Psychiatrie (Dr. med.)", photo: "/fachkraefte/fachkraft-5.jpg", photoDetail: "/fachkraefte/fachkraft-5.jpg", experience: 17, location: "Salzburg", stars: 4.9, reviewCount: 38, languages: ["Deutsch", "Englisch", "Französisch"], tags: ["Affektive Störungen", "PTBS", "Sucht", "Angststörungen"], kassenerstattung: true, verified: true, price: 110, sessionDuration: 50, availability: "thisweek", availabilityText: "Verfügbar diese Woche", nextAppointment: "Mo. 19. Mai, 14:00", angebot: "vor-ort", bio: "Spezialisiert auf affektive Störungen und Sucht biete ich fundierte psychiatrische Unterstützung mit viel Einfühlungsvermögen.",
    bio_en: "Specialised in affective disorders and addiction, I offer sound psychiatric support with great empathy.",
    approach_en: "Psychiatric conditions are complex and individual. I take the time to understand your specific situation and develop a personalised treatment plan.", approach: "Psychiatrische Erkrankungen sind komplex und individuell. Ich nehme mir die Zeit, Deine spezifische Situation zu verstehen und einen personalisierten Behandlungsplan zu entwickeln.", arbeitsweise: ["Spezialisiert", "Einfühlsam", "Fundiert", "Individuell"], qualifikationen: [{ year: "2006", title: "Dr. med. Psychiatrie", institution: "Paracelsus Medizinische Privatuniversität Salzburg" }, { year: "2009", title: "Fachärztin Psychiatrie", institution: "Österreichische Ärztekammer" }, { year: "2013", title: "Zertifizierung Suchttherapie", institution: "Österreichische Gesellschaft für Suchtmedizin" }],
  },
  {
    id: 18, address: { street: "Neubaugasse 28", city: "1070 Wien" }, name: "Tobias Lehner", role: "Psychologischer Psychotherapeut", degree: "Psychologischer Psychotherapeut (M.Sc.)", photo: "/fachkraefte/fachkraft-6.jpg", photoDetail: "/fachkraefte/fachkraft-6.jpg", experience: 6, location: "Wien", stars: 4.7, reviewCount: 15, languages: ["Deutsch", "Englisch"], tags: ["Phobien", "Zwangsstörungen", "Panikattacken", "Stress"], kassenerstattung: false, verified: true, price: 80, sessionDuration: 50, availability: "today", availabilityText: "Heute verfügbar", nextAppointment: "Heute, 14:00", angebot: "beides", bio: "Mit kognitiv-behavioralen Methoden helfe ich Dir, Ängste und Zwänge zu überwinden.",
    bio_en: "Using cognitive-behavioural methods I help you to overcome fears and compulsions.",
    approach_en: "Phobias and OCD are treatable. With established CBT methods we jointly develop strategies that make your life freer again.", approach: "Phobien und Zwangsstörungen sind behandelbar. Mit bewährten KVT-Methoden entwickeln wir gemeinsam Strategien, die Dein Leben wieder freier machen.", arbeitsweise: ["KVT-basiert", "Strukturiert", "Ermutigend", "Evidenzbasiert"], qualifikationen: [{ year: "2017", title: "M.Sc. Psychologie", institution: "Universität Wien" }, { year: "2019", title: "KVT Ausbildung", institution: "Österreichische Gesellschaft für Verhaltenstherapie" }, { year: "2021", title: "Zertifizierung Angststörungen", institution: "Österreichische Angstgesellschaft" }],
  },
  {
    id: 19, address: null, name: "Dr. Petra Haas", role: "Klinische Psychologin", degree: "Klinische Psychologin (PhD)", photo: "/fachkraefte/fachkraft-1.jpg", photoDetail: "/fachkraefte/fachkraft-1.jpg", experience: 16, location: "Wien", stars: 4.8, reviewCount: 29, languages: ["Deutsch", "Englisch", "Türkisch"], tags: ["Trauma", "Migration", "Kulturelle Identität", "Depression"], kassenerstattung: true, verified: true, price: 95, sessionDuration: 50, availability: "thisweek", availabilityText: "Verfügbar diese Woche", nextAppointment: "Di. 20. Mai, 16:00", angebot: "online", bio: "Mit kultureller Sensibilität begleite ich Menschen mit Migrationshintergrund auf ihrem Weg.",
    bio_en: "With cultural sensitivity I accompany people with migration backgrounds on their journey.",
    approach_en: "Cultural identity and migration experiences shape our experience deeply. I offer a space where you feel welcome with all your backgrounds.", approach: "Kulturelle Identität und Migrationserfahrungen prägen unser Erleben tief. Ich biete einen Raum, in dem Du Dich mit all Deinen Hintergründen willkommen fühlst.", arbeitsweise: ["Kulturell sensibel", "Inklusiv", "Tiefgreifend", "Verständnisvoll"], qualifikationen: [{ year: "2007", title: "PhD Klinische Psychologie", institution: "Universität Wien" }, { year: "2010", title: "Approbation Klinische Psychologie", institution: "Österreichische Gesellschaft für Psychologie" }, { year: "2015", title: "Transkulturelle Psychologie", institution: "Institut für interkulturelle Kompetenz Wien" }],
  },
  {
    id: 20, address: { street: "Landstraße 47", city: "4020 Linz" }, name: "Simon Moser", role: "Psychologischer Psychotherapeut", degree: "Psychologischer Psychotherapeut (M.Sc.)", photo: "/fachkraefte/fachkraft-2.jpg", photoDetail: "/fachkraefte/fachkraft-2.jpg", experience: 8, location: "Linz", stars: 4.7, reviewCount: 19, languages: ["Deutsch"], tags: ["Sucht", "Abhängigkeit", "Depression", "Burnout"], kassenerstattung: true, verified: true, price: 80, sessionDuration: 50, availability: "later", availabilityText: "Nächster Termin in 2 Wochen", nextAppointment: "2. Jun, 13:00", angebot: "vor-ort", bio: "Sucht und Depression erfordern besonders viel Verständnis – ich begleite Dich ohne Vorurteile.",
    bio_en: "Addiction and depression require particularly great understanding — I accompany you without prejudice.",
    approach_en: "Dependency is not a weakness — it is an illness that deserves treatment. I accompany you on the path to freedom with patience and without judgement.", approach: "Abhängigkeit ist keine Schwäche – sie ist eine Erkrankung, die Behandlung verdient. Ich begleite Dich auf dem Weg zur Freiheit mit Geduld und ohne Verurteilung.", arbeitsweise: ["Ohne Vorurteile", "Geduldig", "Motivierend", "Unterstützend"], qualifikationen: [{ year: "2015", title: "M.Sc. Psychologie", institution: "Universität Linz" }, { year: "2017", title: "Psychotherapieausbildung", institution: "Österreichischer Bundesverband für Psychotherapie" }, { year: "2019", title: "Zertifizierung Suchttherapie", institution: "Österreichische Gesellschaft für Suchtmedizin" }],
  },
];

export type Therapist = typeof therapists[0];
